### ISSUE TITLE
Setting PYWPS_PROCESSES not set, we are using the processes array directly

### ISSUE THREAD

**Issue by vincent-dinh** [3liz/qgis-wps4server#2]
Hi,

I am trying to install wps4server but stumble across an error when checking localhost:81/cgi-bin/qgis_mapserv.fcgi?SERVICE=WPS

/tmp/pywps.log returns:

PyWPS [2016-06-15 10:06:02,502] INFO: Setting PYWPS_PROCESSES not set, we are using the processes array directly

I have edited pywps.cgi to set the variable PYWPS_PROCESSES to reflect the processes folder of pywps however it doesn t seem to be exported.

Cheers

**Comment by rldhont** [comment]
Hi @vincent-dinh, PYWPS_PROCESSES is not used in qgis-wps4server.
qgis-wps4server does not used a processes folder, it is mde to publish QGIS Processing algorithms through WPS.
The message you refered is just an INFO not an ERROR.

Regards,

**Comment by vincent-dinh** [comment]
Thank you for your reply @rldhont .

I though it was an error because when I try localhost:81/cgi-bin/qgis_mapserv.fcgi?SERVICE=WPS&REQUEST=GetCapabilities 
I get 
`<ServiceExceptionReport version="1.3.0"><ServiceException code="Service configuration error">Service unknown or unsupported</ServiceException></ServiceExceptionReport> .`

I was expecting to see a list of QGIS processing algorithms 

Regards,

**Comment by rldhont** [comment]
So the plugin is not well loaded.
Can you take a look at the qgis-server log ?
You'll find information about plugins.

**Comment by vincent-dinh** [comment]
@rldhont , after investigation if I remove grass from the providers variable in the [qgis] section, the plugin successfully loads. (I have tried successfully all the other providers)

I tried finding which algos was causing the problem, however it appears that they all seem to work fine.
This config of the default.cfg works fine:
`[qgis]
...
providers=grass 
algs= all the algs from grass`

This config cause some trouble:
`[qgis]
...
providers=grass 
#algs=
`

I am not sure what happens. If you have any suggestion to identify the problem let me know and I will give it a try.

config details:
wps4server is installed on debian8 , browser used: firefox , hosted on ovh vps

Cheers
